### ISSUE TITLE
Random question about your SK setup

### ISSUE THREAD

**Issue by megalithic** [j-hui/pokerus#4]
https://github.com/j-hui/pokerus/blob/0f81e26d5d342ae1e67a7e2ecb53d5ac41455fc1/surfingkeys.config/surfingkeys/surfingkeys.js#L380

Hey there @j-hui!

I'm loving your work on fidget.nvim and just discovered you use surfingkeys as well!

One thing I _really_ want to get working is the ability to map `<C-1>` for instance, to `1T` for jumping to tabs 1-10. Realizing your dotfiles repo is not a place for random internet users to ask questions/get help on things you're not even using/doing; I'd still be curious if you've done something like this?

Thanks for your OSS work.

**Comment by j-hui** [comment]
Hey @megalithic !

It's actually been a little while since I've tweaked my surfingkeys config; these days I'm mostly using Qutebrowser (+ Chrome without sk for less cooperative sites). So this might be better asked on the brookhong/surfingkeys repo.

If you've already tried this out yourself and not gotten it to work, my guess is that it's because the keystroke handler is "swallowing" the number key by interpreting it as the number of times you want the following action to take place, e.g., interpreting `4j` as `jjjj`, etc. If this behavior takes precedence over the a mapping from `1T` , then it might just interpret that as `T`. But I haven't looked at the internals very closely so that's just my best guess.

Sorry I couldn't be of more help, but I hope you find an answer!

**Comment by megalithic** [comment]
This is so good, checking qutebrowser out even as we speak!

**Comment by megalithic** [comment]
Just wanted to say thanks again for pointing me to qutebrowser, WOW, literally (n)vim for the browser, both in function and customizability!
